### PR TITLE
fix version and bump version

### PR DESCRIPTION
**Pull request by chpego**
Fix the #218 #207 and bump to new version https://github.com/albertogeniola/MerossIot/compare/0.4.1.0rc7...0.4.1.1rc1

### CODE REVIEW

**Comment by tarheelz** [comment]
Thanks for doing this.

**Comment by adampaulberg** [comment]
thank you

**Comment by tarheelz** [comment]
I think only @albertogeniola has the write access to take this to the finish line.

**Comment by THATDONFC** [comment]
@albertogeniola Can we get this merged please? I don't see a reason for not including a version in manifest.json. Home Assistant will disable this custom component on the next release if this isn't fixed.

**Comment by Raul-7-7** [comment]
Thanks @chpego 
Just a reminder to everyone, this integration is going to stop loading unless the version key is added. 

Do we know if @albertogeniola is still interested in continuing with this project? if not, anyway to get write access to merge the code?

**Comment by atmezferix** [comment]
I believe this is now a breaking change in Home Assistant 2021.6.0 as Meross cloud will no longer work and it looks like it is due to a missing version number.

**Comment by Raul-7-7** [comment]
That is correct. you can edit the json yourself, or someone with access need to up the version so HACS can pull the new files OR just re-install the add-on. 
@atmezferix

**Comment by THATDONFC** [comment]
@atmezferix @Raul-7-7 this should still work. The version number was added to manifest.json in the [merge commit](https://github.com/albertogeniola/meross-homeassistant/commit/da40ede6f5eeb3c07d29acade50dd018ae5fda0b) 7 days ago.

**Comment by Raul-7-7** [comment]
@THATDONFC It was added, however, since the version was not bumped (still Version 1.0.5), HACS did not detect a chance and as a result did NOT pull the latest manifest.json! 

- you can either manually modify the manifest.json locally
- Remove and then re-install in HACS 
- Someone with permission , up the version in Github to 1.0.6 so HACS detect new version and pull it.
Cheers,

**Comment by atmezferix** [comment]
I've added the version line into the manifest.json file locally and restarted home assistant and its all working again now.

Yes HACS wasn't saying there was an update so might be worth someone upping the version so it will detect there is a new version available.

**Comment by cristian7314** [comment]
Ciao. Ho installato la tua ultima versione 1.0.7 ma ancora i miei dispositivi non funzionano. Di seguito lista dei dispositivi:
Msl420
Mssr310r
Mss620
Mss425f
Msl320c

**Pull request merged**
